### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by love010608** [funnyque/easyUpload.js#5]
进度条走完，显示失败，这个上传地址的问题吗？

**Comment by timchueh** [comment]
有successkey和successValue字段用来标识上传成功的，可能是这块需要做一下对应配置

**Comment by love010608** [comment]
加上去也没有效果，action改成本地地址直接上传就失败了，用例子上的地址会吧进度条走完再提示失败。

**Comment by timchueh** [comment]
上传成功要看文件是否真的上传到服务，进度条展示成功依赖于2点:
1.文件长传到服务
2.successkey和successValue字段与接口返回标识的字段匹配

**Comment by love010608** [comment]
那以作者提供的例子为例的话，该如何才能成功上传到本地呢？

**Comment by timchueh** [comment]
首先要搭一个本地服务吧
