### ISSUE TITLE
关于大小配置后文件未超过配置大小却提示了超出

### ISSUE THREAD

**Issue by lrkonepiece** [funnyque/easyUpload.js#7]
`  else if (countDiff <= 0 && fileSize > that.configs.maxCount) {
                                message = '文件大小超出，当前文件' + fileSize + 'M，允许大小为' + that.configs.maxSize + 'M';
                                onAlert(message);
                            }`
easyUploader.jq.js文件中上处代码判断中的maxCount应该改为maxSize

**Comment by timchueh** [comment]
感谢反馈，版本已更新
