### ISSUE TITLE
请教下ie不支持es6导致不能使用怎么解决啊？

### ISSUE THREAD

**Issue by lrkonepiece** [funnyque/easyUpload.js#8]

**Comment by kevincheng201903** [comment]
是的，我也发现这个问题了

**Comment by timchueh** [comment]
es6？插件中有es6语法吗

**Comment by kevincheng201903** [comment]
> es6？插件中有es6语法吗

有的， initPlugin: function (configs) {

            this.configs = Object.assign({}, defaultConfigs, configs);   ，在 Edge下面代码跑不起来

**Comment by kevincheng201903** [comment]
es6 接口

**Comment by funnyque** [comment]
确定是这个原因吗

**Comment by timchueh** [comment]
已将Object.assign替换为assignObject方法
